name: Check PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '*.md'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Using Caches
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Grant Execute Permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
