name: Docker

on:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE
      - '**.md'
    branches-ignore:
      - 'releases/**'

  release:
    types:
      - published

  workflow_dispatch:

env:
  DOCKER_BASE_NAME: slashnephy/tweetstorm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (master)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_BASE_NAME }}:latest

      - name: Build & Push (dev)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_BASE_NAME }}:dev

      - name: Build & Push (Release)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_BASE_NAME }}:${{ github.event.release.tag_name }}

      # 2FA を無効化する必要がある
      # https://github.com/peter-evans/dockerhub-description#action-inputs
      # - name: Update Docker Hub description
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   uses: peter-evans/dockerhub-description@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ env.DOCKER_BASE_NAME }}
